version: '3'
services:
#mssql docker
  onlinecourseapp-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - onlinecoursenet

  onlinecourseapp-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:OnlineCourseApp=Server=onlinecourseapp-sql,1433;Database=160065;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 64315:5010
    networks:
      - onlinecoursenet    
    links:
      - onlinecourseapp-sql
    depends_on:
      - onlinecourseapp-sql
      
networks:
 onlinecoursenet:
    driver: bridge   