version: '3'
services:
#mssql docker
  onlinecourseapp-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - onlinecoursenet

  eprodaja-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=onlinecourseapp-sql,1433;Database=eProdajaVjezbe;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 5010:5010
    networks:
      - eprodajanet      
    links:
      - eprodaja-sql
    depends_on:
      - eprodaja-sql
      
networks:
  eprodajanet:
    driver: bridge   